# Generated by Django 6.0.6 on 2026-07-29 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorOwnPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('x', 'X')], default='youtube', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monitor_own_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('x', 'X')], default='youtube', max_length=20)),
                ('source_handle', models.CharField(max_length=120)),
                ('youtube_id', models.CharField(blank=True, max_length=120)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('kind', models.CharField(choices=[('COMPETITOR', 'Competitor'), ('OWN', 'Own')], default='COMPETITOR', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=400)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monitor_channels',
                'ordering': ['-created_at'],
                'unique_together': {('source', 'source_handle')},
            },
        ),
        migrations.CreateModel(
            name='MonitorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=120)),
                ('youtube_video_id', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=600)),
                ('status', models.CharField(choices=[('OPEN', 'They have posted'), ('WORKING', "We're posting")], default='OPEN', max_length=12)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('unread', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='nimble_app.monitorchannel')),
            ],
            options={
                'db_table': 'monitor_alerts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='monitor_ale_status_cbd415_idx'), models.Index(fields=['channel', 'created_at'], name='monitor_ale_channel_19a906_idx')],
                'unique_together': {('channel', 'item_id')},
            },
        ),
    ]
