# Generated by Django 6.0.6 on 2026-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimble_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorchannel',
            name='consecutive_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitorchannel',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
