# Generated by Django 6.0.6 on 2026-07-31 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career_app', '0033_alter_documentauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PERSONAL', 'Personal'), ('SHARED', 'Shared / team'), ('SYSTEM', 'System (catch-all)')], default='PERSONAL', max_length=10)),
                ('address', models.CharField(db_index=True, max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9._-]{0,63}@mail\\.tiesverse\\.com$', 'Address must look like name@mail.tiesverse.com (lowercase letters, digits, . _ -).')])),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('access_password', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('daily_send_limit', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='career_app.onboardingsubmission')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mailboxes',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='MailboxGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='mail_app.mailbox')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mailbox_grants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUT', 'Sent'), ('IN', 'Received')], max_length=3)),
                ('peer', models.CharField(blank=True, max_length=255)),
                ('to', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('snippet', models.CharField(blank=True, max_length=300)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=500)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('thread_key', models.CharField(blank=True, db_index=True, max_length=500)),
                ('ses_message_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('received', 'Received')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('spam_verdict', models.CharField(blank=True, max_length=20)),
                ('virus_verdict', models.CharField(blank=True, max_length=20)),
                ('s3_key', models.CharField(blank=True, db_index=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail_app.mailbox')),
                ('sent_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('created_mailbox', 'Created mailbox'), ('updated_mailbox', 'Updated mailbox'), ('archived_mailbox', 'Archived mailbox'), ('restored_mailbox', 'Restored mailbox'), ('set_password', 'Set/rotated shared password'), ('granted_access', 'Granted access'), ('revoked_access', 'Revoked access'), ('viewed_mailbox', 'Viewed mailbox'), ('read_message', 'Read message'), ('deleted_message', 'Deleted message'), ('shared_login', 'Shared-mailbox login')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='mail_app.mailbox')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mail_app.mailmessage')),
            ],
            options={
                'db_table': 'mail_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['kind', 'is_active'], name='mailboxes_kind_adb891_idx'),
        ),
        migrations.AddIndex(
            model_name='mailbox',
            index=models.Index(fields=['member'], name='mailboxes_member__d6e596_idx'),
        ),
        migrations.AddIndex(
            model_name='mailboxgrant',
            index=models.Index(fields=['user'], name='mailbox_gra_user_id_bc3c8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailboxgrant',
            unique_together={('mailbox', 'user')},
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['mailbox', 'direction', '-created_at'], name='mail_messag_mailbox_b99b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['thread_key'], name='mail_messag_thread__8b9360_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['mailbox', 'is_deleted'], name='mail_messag_mailbox_80f072_idx'),
        ),
        migrations.AddIndex(
            model_name='mailauditlog',
            index=models.Index(fields=['mailbox', '-created_at'], name='mail_audit__mailbox_1ec876_idx'),
        ),
    ]
