# Generated by Django 6.0.6 on 2026-08-04 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('storage_key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mail_attachments',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.JSONField(blank=True, default=list)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('thread_key', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mail_drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MailNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_key', models.CharField(db_index=True, max_length=500)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mail_notes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailSsoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mail_sso_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='send_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailauditlog',
            name='action',
            field=models.CharField(choices=[('created_mailbox', 'Created mailbox'), ('updated_mailbox', 'Updated mailbox'), ('archived_mailbox', 'Archived mailbox'), ('restored_mailbox', 'Restored mailbox'), ('set_password', 'Set/rotated shared password'), ('granted_access', 'Granted access'), ('revoked_access', 'Revoked access'), ('viewed_mailbox', 'Viewed mailbox'), ('read_message', 'Read message'), ('deleted_message', 'Deleted message'), ('restored_message', 'Restored message'), ('updated_avatar', 'Updated mailbox picture'), ('shared_login', 'Shared-mailbox login'), ('sso_login', 'Signed in from the admin panel'), ('sent_scheduled', 'Sent a scheduled message')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mailmessage',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('received', 'Received')], default='queued', max_length=10),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['mailbox', 'starred'], name='mail_messag_mailbox_e82360_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['status', 'send_at'], name='mail_messag_status_c72d05_idx'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_app.mailmessage'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maildraft',
            name='created_by_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maildraft',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='mail_app.mailbox'),
        ),
        migrations.AddField(
            model_name='mailattachment',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_app.maildraft'),
        ),
        migrations.AddField(
            model_name='mailnote',
            name='author_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailnote',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mail_app.mailbox'),
        ),
        migrations.AddIndex(
            model_name='maildraft',
            index=models.Index(fields=['mailbox', '-updated_at'], name='mail_drafts_mailbox_837be8_idx'),
        ),
        migrations.AddIndex(
            model_name='mailattachment',
            index=models.Index(fields=['message'], name='mail_attach_message_4e6dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='mailattachment',
            index=models.Index(fields=['draft'], name='mail_attach_draft_i_c972af_idx'),
        ),
        migrations.AddIndex(
            model_name='mailnote',
            index=models.Index(fields=['mailbox', 'thread_key', 'created_at'], name='mail_notes_mailbox_85ee64_idx'),
        ),
    ]
