# Generated by Django 6.0.6 on 2026-08-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0002_mailattachment_maildraft_mailnote_mailssoticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='bcc',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
