# Generated by Django 6.0.6 on 2026-08-04 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0003_mailmessage_bcc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('done', 'Finished'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to='mail_app.mailbox')),
            ],
            options={
                'db_table': 'mail_bulk_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='mail_bulk_j_status_9f6f79_idx'), models.Index(fields=['mailbox', '-created_at'], name='mail_bulk_j_mailbox_228c95_idx')],
            },
        ),
    ]
