# Generated by Django 6.0.6 on 2026-08-04 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0004_mailbulkjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mailattachment',
            name='bulk_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail_app.mailbulkjob'),
        ),
        migrations.AddIndex(
            model_name='mailattachment',
            index=models.Index(fields=['bulk_job'], name='mail_attach_bulk_jo_fc7b77_idx'),
        ),
    ]
