# Generated by Django 6.0.6 on 2026-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0005_mailattachment_bulk_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailauditlog',
            name='action',
            field=models.CharField(choices=[('created_mailbox', 'Created mailbox'), ('updated_mailbox', 'Updated mailbox'), ('archived_mailbox', 'Archived mailbox'), ('restored_mailbox', 'Restored mailbox'), ('set_password', 'Set/rotated shared password'), ('granted_access', 'Granted access'), ('revoked_access', 'Revoked access'), ('viewed_mailbox', 'Viewed mailbox'), ('read_message', 'Read message'), ('deleted_message', 'Deleted message'), ('restored_message', 'Restored message'), ('updated_avatar', 'Updated mailbox picture'), ('shared_login', 'Shared-mailbox login'), ('sso_login', 'Signed in from the admin panel'), ('sent_scheduled', 'Sent a scheduled message'), ('bulk_started', 'Started a bulk send')], max_length=30),
        ),
    ]
