# Generated by Django 6.0.6 on 2026-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0006_alter_mailauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='maildraft',
            name='body_html',
            field=models.TextField(blank=True),
        ),
    ]
