# Generated by Django 6.0.6 on 2026-08-06 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_app', '0008_alter_mailauditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailauditlog',
            name='action',
            field=models.CharField(choices=[('created_mailbox', 'Created mailbox'), ('updated_mailbox', 'Updated mailbox'), ('archived_mailbox', 'Archived mailbox'), ('restored_mailbox', 'Restored mailbox'), ('set_password', 'Set/rotated shared password'), ('granted_access', 'Granted access'), ('revoked_access', 'Revoked access'), ('viewed_mailbox', 'Viewed mailbox'), ('read_message', 'Read message'), ('deleted_message', 'Deleted message'), ('restored_message', 'Restored message'), ('updated_avatar', 'Updated mailbox picture'), ('shared_login', 'Shared-mailbox login'), ('sso_login', 'Signed in from the admin panel'), ('sent_scheduled', 'Sent a scheduled message'), ('bulk_started', 'Started a bulk send'), ('created_task', 'Turned a message into a task'), ('granted_admin', 'Made someone a mail administrator'), ('revoked_admin', 'Removed mail administration'), ('updated_mailbox_owner', 'Reassigned a mailbox')], max_length=30),
        ),
        migrations.CreateModel(
            name='MailAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('user_email', models.CharField(blank=True, max_length=254)),
                ('granted_by_name', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_admins',
                'ordering': ['user_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_mail_admin_user')],
            },
        ),
    ]
