# Generated by Django 6.0.6 on 2026-06-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='session_timeout',
            field=models.IntegerField(default=10),
        ),
    ]
