# Generated by Django 6.0.6 on 2026-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_userprofile_can_delegate_perm'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=300)),
                ('from_name', models.CharField(blank=True, help_text='Sender alias / display name', max_length=200)),
                ('from_email', models.EmailField(blank=True, help_text='Blank = use the default sender', max_length=254)),
                ('body_html', models.TextField(help_text='HTML with {{placeholder}} tokens')),
                ('is_enabled', models.BooleanField(default=False, help_text='Off = printed to console, not sent')),
                ('allow_attachment', models.BooleanField(default=False, help_text='May carry a PDF (e.g. certificates)')),
                ('variables', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['name'],
            },
        ),
    ]
