# Generated by Django 6.0.6 on 2026-07-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='content_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body_html',
            field=models.TextField(help_text='Rendered HTML (generated from content_json)'),
        ),
    ]
