# Generated by Django 6.0.6 on 2026-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_emailtemplate_content_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='html_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
