# Generated by Django 6.0.6 on 2026-07-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0008_emailtemplate_html_mode_emailtemplate_is_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('template_key', models.CharField(max_length=64)),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('recipient_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'email_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
