# Generated by Django 6.0.6 on 2026-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0009_emailcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('spotlight', 'Spotlight (hero card)'), ('insights', 'Latest in Insights'), ('engagements', 'Latest in Engagements')], default='spotlight', max_length=20)),
                ('kind', models.CharField(choices=[('report', 'Report'), ('insight', 'Insight'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('event', 'Event'), ('podcast', 'Podcast')], default='report', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, help_text='Category / meta line', max_length=300)),
                ('image_url', models.CharField(blank=True, max_length=800)),
                ('link_url', models.CharField(blank=True, help_text='Where the card links to', max_length=800)),
                ('cta_label', models.CharField(blank=True, help_text='e.g. "Read the report"', max_length=100)),
                ('date_label', models.CharField(blank=True, help_text='e.g. "Jun 04, 2026"', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower shows first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'featured_content',
                'ordering': ['section', 'order', '-created_at'],
            },
        ),
    ]
