# Generated by Django 6.0.6 on 2026-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0010_featuredcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.CharField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('template_key', models.CharField(blank=True, max_length=64)),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('context', models.CharField(db_index=True, default='campaign', max_length=40)),
                ('event_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('event_type', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('sent_by', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'email_send_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
