# Generated by Django 6.0.6 on 2026-07-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_emailsendlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendlog',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
