# Generated by Django 6.0.6 on 2026-07-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0016_campaign_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='batch_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='batch_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='batch_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='job_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='notify_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
