# Generated by Django 6.0.6 on 2026-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0017_emailcampaign_batch_index_emailcampaign_batch_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNavCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_slug', models.SlugField(help_text='WordPress category slug', max_length=120)),
                ('wp_category_id', models.IntegerField(default=0, help_text='WordPress category ID (for fast lookups)')),
                ('label', models.CharField(help_text='Friendly label shown in the nav, e.g. "Map illustrations"', max_length=120)),
                ('order', models.IntegerField(default=0, help_text='Lower shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_nav_categories',
                'ordering': ['order', 'id'],
            },
        ),
    ]
