# Generated by Django 6.0.6 on 2026-07-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0018_sitenavcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_delegate_permissions', 'Can delegate own permissions to team members'), ('can_edit_articles', 'Can write and save article/report drafts'), ('can_publish_articles', 'Can publish and edit articles/reports')]},
        ),
    ]
