# Generated by Django 6.0.6 on 2026-08-16 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0021_seed_doc_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, max_length=80)),
                ('utm_medium', models.CharField(blank=True, max_length=80)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('utm_content', models.CharField(blank=True, max_length=120)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('junk', 'Junk')], db_index=True, default='active', max_length=20)),
                ('status_reason', models.CharField(blank=True, max_length=200)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_mailed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mail_contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'email'], name='mail_contac_status_262154_idx')],
            },
        ),
        migrations.CreateModel(
            name='MailContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(db_index=True, max_length=200)),
                ('event_title', models.CharField(blank=True, max_length=300)),
                ('event_date', models.CharField(blank=True, max_length=80)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts_app.mailcontact')),
            ],
            options={
                'db_table': 'mail_contact_events',
                'ordering': ['-registered_at', '-id'],
                'unique_together': {('contact', 'event_key')},
            },
        ),
    ]
