# Generated by Django 6.0.6 on 2026-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0004_structured_fields_and_new_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-applied_at'], 'permissions': [('can_review_leave', 'Can approve or reject leave requests (HR only)')]},
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='escalated_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='escalated_to_advisory',
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='work_report',
            field=models.TextField(blank=True, help_text='What the member did today'),
        ),
        migrations.AlterField(
            model_name='documentauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick'), ('casual', 'Casual'), ('personal', 'Personal'), ('unpaid', 'Unpaid'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='memberaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to_department',
            field=models.CharField(blank=True, help_text='If set, task goes to full department', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
