# Generated by Django 6.0.6 on 2026-07-04 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0006_alter_asset_assigned_by_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('offboarded', 'Offboarded')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='OffboardingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offboard_type', models.CharField(choices=[('resignation', 'Resignation'), ('end_of_internship', 'End of internship'), ('termination', 'Termination'), ('other', 'Other')], default='resignation', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('desired_last_day', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_name', models.CharField(blank=True, max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding_requests', to='career_app.onboardingsubmission')),
                ('reviewed_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboardings_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboarding_requests',
                'ordering': ['-applied_at'],
                'permissions': [('can_review_offboarding', 'Can approve, reject or revoke offboarding (HR only)')],
            },
        ),
    ]
