# Generated by Django 6.0.6 on 2026-07-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0007_alter_onboardingsubmission_status_offboardingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField(help_text='Date the reported week ends')),
                ('summary', models.TextField(help_text='What the team did this week')),
                ('wins', models.TextField(blank=True, help_text='Key wins / highlights')),
                ('blockers', models.TextField(blank=True, help_text='Blockers / needs attention')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_updates_submitted', to=settings.AUTH_USER_MODEL)),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_updates', to='career_app.onboardingsubmission')),
            ],
            options={
                'db_table': 'weekly_updates',
                'ordering': ['-week_ending', '-created_at'],
            },
        ),
    ]
