# Generated by Django 6.0.6 on 2026-07-05 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0008_weeklyupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('photo_url', models.URLField(blank=True)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('otp_pending', 'OTP pending'), ('verified', 'Awaiting HR'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='otp_pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signups_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'self_signups',
                'ordering': ['-created_at'],
            },
        ),
    ]
