# Generated by Django 6.0.6 on 2026-07-07 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0011_form_formresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('owner_role', models.CharField(blank=True, help_text="'advisory' or 'team_lead'", max_length=20)),
                ('scope', models.CharField(choices=[('all', 'All departments'), ('departments', 'Selected departments')], default='departments', max_length=15)),
                ('departments', models.JSONField(blank=True, default=list)),
                ('department_priorities', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('original_deadline', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chat_purge_after_days', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to='career_app.onboardingsubmission')),
                ('created_by_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='career_app.project'),
        ),
        migrations.CreateModel(
            name='ProjectDeadlineChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_deadline', models.DateField(blank=True, null=True)),
                ('new_deadline', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_deadline_changes', to='career_app.onboardingsubmission')),
                ('changed_by_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_deadline_changes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_changes', to='career_app.project')),
            ],
            options={
                'db_table': 'project_deadline_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='career_app.onboardingsubmission')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='career_app.project')),
            ],
            options={
                'db_table': 'project_members',
                'ordering': ['role', 'added_at'],
                'unique_together': {('project', 'member')},
            },
        ),
    ]
