# Generated by Django 6.0.6 on 2026-07-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0015_projectattachment_projectmilestone_projectteam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='team',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='career_app.projectteam'),
        ),
    ]
