# Generated by Django 6.0.6 on 2026-07-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0016_remove_projectmember_team_projectmember_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='career_app.projectteam'),
        ),
    ]
