# Generated by Django 6.0.6 on 2026-07-08 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0017_projectmessage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='career_app.onboardingsubmission'),
        ),
    ]
