# Generated by Django 6.0.6 on 2026-07-08 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0018_projectteam_description_projectteam_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_done', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='career_app.onboardingsubmission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='career_app.task')),
            ],
            options={
                'db_table': 'task_steps',
                'ordering': ['order', 'id'],
            },
        ),
    ]
