# Generated by Django 6.0.6 on 2026-07-08 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0021_weeklyupdatecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='auto_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worksession',
            name='custom_task',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='worksession',
            name='progress_after',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyWorkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('first_check_in', models.DateTimeField(blank=True, null=True)),
                ('last_check_out', models.DateTimeField(blank=True, null=True)),
                ('auto_closed_count', models.PositiveIntegerField(default=0)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_summaries', to='career_app.onboardingsubmission')),
            ],
            options={
                'db_table': 'daily_work_summaries',
                'ordering': ['-date'],
                'unique_together': {('member', 'date')},
            },
        ),
    ]
