# Generated by Django 6.0.6 on 2026-07-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0024_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalnote',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
