# Generated by Django 6.0.6 on 2026-07-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0026_formapikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormApiKey',
        ),
    ]
