# Generated by Django 6.0.6 on 2026-07-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0028_alter_onboardingsubmission_portal_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingsubmission',
            name='portal_role',
            field=models.CharField(blank=True, choices=[('member', 'Member'), ('intern', 'Intern'), ('team_lead', 'Team Lead'), ('advisory', 'Advisory'), ('hr', 'HR'), ('admin', 'Admin'), ('contractual', 'Contractual'), ('superuser', 'Super User')], help_text='Portal access level assigned by HR on verify', max_length=20),
        ),
    ]
