# Generated by Django 6.0.6 on 2026-07-16 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0029_alter_onboardingsubmission_portal_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='worksession',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='approved_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='worksession',
            name='approved_by_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
