# Generated by Django 6.0.6 on 2026-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0030_worksession_approval_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsubmission',
            name='certificate_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
