# Generated by Django 6.0.6 on 2026-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0031_onboardingsubmission_certificate_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_code', models.CharField(max_length=2, unique=True)),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Crew series',
                'db_table': 'crew_series',
            },
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('OFFBOARDED', 'Offboarded'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='crew_id',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='deactivation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='identity_class',
            field=models.CharField(blank=True, choices=[('EMP', 'Employee'), ('INT', 'Intern'), ('TRN', 'Trainee'), ('CON', 'Contractor'), ('FRL', 'Freelancer'), ('CNS', 'Consultant'), ('CLI', 'Client'), ('PRT', 'Partner'), ('INS', 'Instructor'), ('GST', 'Guest'), ('ALM', 'Alumni')], max_length=3),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
