# Generated by Django 6.0.6 on 2026-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0032_crewseries_onboardingsubmission_account_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentauditlog',
            name='action',
            field=models.CharField(choices=[('issued', 'Issued'), ('revoked', 'Revoked'), ('changed', 'Changed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='documentauditlog',
            name='doc_type',
            field=models.CharField(choices=[('offer_letter', 'Offer Letter'), ('internship_cert', 'Internship Certificate'), ('lor', 'Letter of Recommendation'), ('noc', 'No Objection Certificate'), ('crew_id', 'Crew ID'), ('identity_class', 'Identity Class'), ('account_status', 'Account Status')], max_length=30),
        ),
    ]
