# Generated by Django 6.0.6 on 2026-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0033_alter_documentauditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingsubmission',
            name='notify_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingsubmission',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
