# Generated by Django 6.0.6 on 2026-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0034_onboardingsubmission_notify_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdepartment',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
    ]
