# Generated by Django 6.0.6 on 2026-08-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0035_hrdepartment_is_restricted'),
        ('mail_app', '0008_alter_mailauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_mail_from',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='source_mail_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='mail_app.mailmessage'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_mail_subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
