# Generated by Django 6.0.6 on 2026-08-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0036_task_source_mail_from_task_source_mail_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='edit_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
