# Generated by Django 6.0.6 on 2026-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0037_formresponse_edit_count_formresponse_edit_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='referrer',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
    ]
