# Generated by Django 6.0.6 on 2026-08-02 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career_app', '0033_alter_documentauditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('content_type', models.CharField(choices=[('carousel', 'Carousel / Static'), ('reel', 'Reel / Short'), ('story', 'Story'), ('article', 'Article'), ('video', 'Long-form Video'), ('podcast', 'Podcast'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('scripting', 'Scripting'), ('design', 'Design'), ('editing', 'Editing'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published')], db_index=True, default='idea', max_length=20)),
                ('doc_url', models.URLField(blank=True, max_length=1000)),
                ('extra_links', models.JSONField(blank=True, default=list)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, db_index=True, null=True)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('posting_url', models.URLField(blank=True, max_length=1000)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('effort', models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_assignees', models.ManyToManyField(blank=True, related_name='content_items_writing', to='career_app.onboardingsubmission')),
                ('created_by_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('graphics_assignees', models.ManyToManyField(blank=True, related_name='content_items_graphics', to='career_app.onboardingsubmission')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='career_app.task')),
            ],
            options={
                'db_table': 'content_items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('verb', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status changed'), ('rescheduled', 'Rescheduled'), ('assigned', 'Assignees changed'), ('commented', 'Commented'), ('task_linked', 'Task linked'), ('deleted', 'Deleted')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='content_app.contentitem')),
            ],
            options={
                'db_table': 'content_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['status', 'order'], name='content_ite_status_b58a03_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['release_date'], name='content_ite_release_0828c4_idx'),
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['due_date'], name='content_ite_due_dat_fe22f0_idx'),
        ),
        migrations.AddIndex(
            model_name='contentactivity',
            index=models.Index(fields=['item', '-created_at'], name='content_act_item_id_559c92_idx'),
        ),
    ]
