# Generated by Django 6.0.6 on 2026-08-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0033_alter_documentauditlog_action_and_more'),
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='content_items_all', to='career_app.task'),
        ),
    ]
