# Generated by Django 6.0.6 on 2026-08-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0034_onboardingsubmission_notify_whatsapp_and_more'),
        ('content_app', '0002_contentitem_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='notify_on_assign',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(blank=True, max_length=20)),
                ('template', models.CharField(blank=True, max_length=100)),
                ('params', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, max_length=10)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('wamid', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='content_app.contentitem')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='career_app.onboardingsubmission')),
                ('sent_by_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_whatsapp_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='content_wha_status_9f3c12_idx')],
            },
        ),
    ]
