# Generated by Django 6.0.6 on 2026-08-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_contentitem_notify_on_assign_whatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('order', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'content categories',
                'db_table': 'content_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contentitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='assets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='media_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='content_app.contentcategory'),
        ),
    ]
