# Generated by Django 6.0.6 on 2026-08-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0036_task_source_mail_from_task_source_mail_message_and_more'),
        ('content_app', '0004_contentcategory_contentitem_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='editor_assignees',
            field=models.ManyToManyField(blank=True, related_name='content_items_editing', to='career_app.onboardingsubmission'),
        ),
    ]
