# Generated by Django 4.2.11 on 2026-07-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0002_alter_docpage_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpage',
            name='allowed_teams',
            field=models.JSONField(blank=True, default=list, help_text='Team IDs that can access this encrypted doc'),
        ),
        migrations.AddField(
            model_name='docpage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('encrypted', 'Encrypted (Internal)')], default='public', max_length=20),
        ),
    ]
