# Generated by Django 6.0.6 on 2026-07-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0003_docpage_allowed_teams_docpage_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docpage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('protected', 'Protected (any signed-in employee)'), ('encrypted', 'Encrypted (specific teams)')], default='public', max_length=20),
        ),
    ]
