"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_INSECURE_SECRET = 'django-insecure-ckk$((ll8=s^xa^429nn_*v5(yv_*l974yni802g4rki%j#h&$'
SECRET_KEY = (
    os.environ.get('SECRET_KEY')
    or os.environ.get('JWT_SECRET')
    or _INSECURE_SECRET
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() != 'false'

# Cloudflare Turnstile — when set, the login endpoint requires a valid token.
# Empty = disabled (login unchanged), so it's safe to deploy before configuring.
TURNSTILE_SECRET_KEY = os.environ.get('TURNSTILE_SECRET_KEY', '')

# Never run in production signing JWTs/sessions with the public fallback key.
if not DEBUG and SECRET_KEY == _INSECURE_SECRET:
    raise RuntimeError('SECRET_KEY (or JWT_SECRET) must be set in production.')

CERTIFICATE_GENERATOR_API_URL = os.environ.get(
    'CERTIFICATE_GENERATOR_API_URL',
    'https://auto-document-generator-backend.onrender.com',
).rstrip('/')

_allowed = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()] or ['localhost', '127.0.0.1']

# ── Security headers ──────────────────────────────────────────────────────
# Always safe: block MIME-sniffing and framing.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
# Behind nginx TLS: tell Django the original request was HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Transport/cookie hardening only in production (would break local http dev).
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

_cors_extra = [h.strip() for h in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if h.strip()]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://tiesverse.com",
    "https://www.tiesverse.com",
] + _cors_extra

# Allow the landing site to POST to the public registration endpoint
CORS_URLS_REGEX = r'^/api/.*$'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'tiesverse_app',
    'career_app',
    'webinar_app',
    'accounts_app',
    'learn_app',
    'docs_app',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Scoped rate limits — applied only to the sensitive public/auth endpoints
    # (see throttle_scope on those views), so normal admin usage and the public
    # website feeds are untouched. Keyed by client IP.
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'signup': '8/min',
        'otp': '12/min',
        'password_reset': '5/min',
        'public_form': '20/min',
        'verify': '30/min',
    },
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Allow signing in with either username or email (matches the "Username or Email"
# login field). The default ModelBackend stays as a fallback.
AUTHENTICATION_BACKENDS = [
    'accounts_app.auth_backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'career_app.middleware.DataApiCorsMiddleware',   # opens CORS for /api/data/v1/ (before CorsMiddleware)
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'supabase_db.sqlite3',
        # Wait up to 30s for a write lock instead of erroring instantly — the
        # campaign worker process and the web workers both write here.
        'OPTIONS': {'timeout': 30},
    },
    'turso_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'turso_db.sqlite3',
    }
}

DATABASE_ROUTERS = ['config.routers.AppRouter']

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media Storage settings removed per request to disconnect Cloudinary

# ---------------------------------------------------------
# Cloudflare (career candidates — D1 database)
# ---------------------------------------------------------
CLOUDFLARE_ACCOUNT_ID = os.environ.get('CLOUDFLARE_ACCOUNT_ID', '')
CLOUDFLARE_D1_DATABASE_ID = os.environ.get('CLOUDFLARE_D1_DATABASE_ID', '')
CLOUDFLARE_API_TOKEN = os.environ.get('CLOUDFLARE_API_TOKEN', '')
CLOUDFLARE_R2_ACCESS_KEY_ID = os.environ.get('CLOUDFLARE_R2_ACCESS_KEY_ID', '')
CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.environ.get('CLOUDFLARE_R2_SECRET_ACCESS_KEY', '')
CLOUDFLARE_R2_BUCKET = os.environ.get('CLOUDFLARE_R2_BUCKET', 'career-tiesverse')

# ---------------------------------------------------------
# Cloudinary (image hosting for landing/webinar content)
# Admins upload images via /api/media/upload/; we store the returned
# secure_url in the model's *_url field.
# ---------------------------------------------------------
import cloudinary
cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME', ''),
    api_key=os.environ.get('CLOUDINARY_API_KEY', ''),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET', ''),
    secure=True,
)
CLOUDINARY_UPLOAD_FOLDER = os.environ.get('CLOUDINARY_UPLOAD_FOLDER', 'tiesverse_admin')

# ---------------------------------------------------------
# Turso (event / webinar registrations)
# TURSO_DATABASE_URL  — e.g. https://dbname-org.turso.io
# TURSO_AUTH_TOKEN    — JWT token from Turso dashboard
# (TURSO_USER / TURSO_DB_PASSWORD are the platform login, not the DB token)
# ---------------------------------------------------------
TURSO_DATABASE_URL = os.environ.get('TURSO_DATABASE_URL', '')
TURSO_AUTH_TOKEN = os.environ.get('TURSO_AUTH_TOKEN', '')

# Mail-merge campaigns can carry per-recipient certificate PDFs (base64) in the
# request body, so allow larger JSON bodies than Django's 2.5 MB default.
DATA_UPLOAD_MAX_MEMORY_SIZE = 40 * 1024 * 1024   # 40 MB

# How long certificate send-audit rows are kept before auto-deletion (the PDFs
# themselves are never stored — only lightweight log rows). 0 = purge on next send.
CAMPAIGN_CERT_RETENTION_DAYS = int(os.environ.get('CAMPAIGN_CERT_RETENTION_DAYS', '30'))

# How many certificates a campaign generates+sends in parallel (server-side).
CAMPAIGN_CONCURRENCY = int(os.environ.get('CAMPAIGN_CONCURRENCY', '8'))

# Target max size (KB) for an emailed certificate PDF. Generated PDFs are
# downsampled (via Ghostscript) toward this cap before attaching.
CERT_MAX_KB = int(os.environ.get('CERT_MAX_KB', '600'))

# ---------------------------------------------------------
# AWS SES (registration confirmation emails)
# ---------------------------------------------------------
# WordPress site (managed from the admin panel via a server-side proxy).
WORDPRESS_URL = os.environ.get('WORDPRESS_URL', '')
WORDPRESS_USER = os.environ.get('WORDPRESS_USER', '')
WORDPRESS_APP_PASSWORD = os.environ.get('WORDPRESS_APP_PASSWORD', '')

AWS_SES_ACCESS_KEY_ID = os.environ.get('AWS_SES_ACCESS_KEY_ID', '')
AWS_SES_SECRET_ACCESS_KEY = os.environ.get('AWS_SES_SECRET_ACCESS_KEY', '')
AWS_SES_REGION = os.environ.get('AWS_SES_REGION', 'ap-south-1')
SES_FROM_EMAIL = os.environ.get('SES_FROM_EMAIL', 'noreply@tiesverse.com')

# Developer/infra dashboard — only these emails (plus superusers) can see /technical
DEVELOPER_EMAILS = [
    e.strip().lower()
    for e in os.environ.get('DEVELOPER_EMAILS', 'ashutosp865@gmail.com').split(',')
    if e.strip()
]

# Offer letters are emailed from the no-reply careers address. Sending stays
# DISABLED until careers@tiesverse.com is verified in SES — flip
# OFFER_EMAIL_ENABLED=True in env to go live.
SES_CAREERS_FROM_EMAIL = os.environ.get('SES_CAREERS_FROM_EMAIL', 'careers@tiesverse.com')
OFFER_EMAIL_ENABLED = os.environ.get('OFFER_EMAIL_ENABLED', 'False').lower() == 'true'

WEBSITE_URL = os.environ.get('WEBSITE_URL', 'https://tiesverse.com')
# Base URL of THIS admin portal frontend — used to build password-reset links.
ADMIN_PORTAL_URL = os.environ.get('ADMIN_PORTAL_URL', 'http://localhost:5173')
ONBOARDING_EMAIL_ENABLED = os.environ.get('ONBOARDING_EMAIL_ENABLED', 'False').lower() == 'true'

# Additional per-purpose email switches. All default OFF (emails are stubbed to
# the console) until the SES sender addresses are verified in production.
CERT_EMAIL_ENABLED = os.environ.get('CERT_EMAIL_ENABLED', 'False').lower() == 'true'
PASSWORD_RESET_EMAIL_ENABLED = os.environ.get('PASSWORD_RESET_EMAIL_ENABLED', 'False').lower() == 'true'

RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')

# ── Google Calendar (interview scheduling — OAuth 2.0 user credentials) ──
# We use OAuth (not a service-account key) because Workspace "secure by default"
# blocks SA key creation. Get the refresh token once with get_google_refresh_token.py.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')
GOOGLE_OAUTH_REFRESH_TOKEN = os.environ.get('GOOGLE_OAUTH_REFRESH_TOKEN', '')
GOOGLE_CAL_TIMEZONE = os.environ.get('GOOGLE_CAL_TIMEZONE', 'Asia/Kolkata')

# ── Self-service signup: the one shared hashed link's secret ──────────────────
# The public signup URL is /signup/<SIGNUP_LINK_HASH>. Share it with interns/members.
SIGNUP_LINK_HASH = os.environ.get('SIGNUP_LINK_HASH', '')

# ── Cache: Redis in production, in-process memory in dev ──────────────────────
# Set REDIS_URL (e.g. redis://127.0.0.1:6379/1) in prod to offload hot reads
# (public feeds, gates, event lists) from the DB / external APIs. No-op locally.
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 60,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'tiesverse-local',
        }
    }

# ── Behind nginx / HTTPS in production ───────────────────────────────────────
# nginx terminates TLS and proxies plain HTTP to gunicorn; this header lets
# Django know the original request was HTTPS (fixes CSRF/secure-cookie/redirects
# and correct absolute URLs for the Django admin login form).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# Keep implicit primary keys aligned with the existing migrations.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
