# Generated by Django 6.0.6 on 2026-08-02 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career_app', '0035_hrdepartment_is_restricted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ Pound Sterling'), ('AUD', 'A$ Australian Dollar'), ('SGD', 'S$ Singapore Dollar'), ('AED', 'AED UAE Dirham'), ('CAD', 'C$ Canadian Dollar'), ('JPY', '¥ Japanese Yen')], default='INR', max_length=3)),
                ('amount_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fx_date', models.DateField(blank=True, null=True)),
                ('fx_missing', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('camera', 'Camera / Gear'), ('accessory', 'Accessory'), ('software', 'Software licence'), ('subscription', 'Subscription'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=20)),
                ('serial', models.CharField(blank=True, max_length=120)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=10)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('assigned', 'Assigned'), ('repair', 'In repair'), ('retired', 'Retired'), ('lost', 'Lost')], db_index=True, default='in_stock', max_length=12)),
                ('assigned_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_assets', to='career_app.onboardingsubmission')),
                ('created_by_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=3)),
                ('rate_to_inr', models.DecimalField(decimal_places=6, max_digits=12)),
                ('on_date', models.DateField(db_index=True)),
                ('source', models.CharField(default='frankfurter', max_length=40)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_exchange_rates',
                'ordering': ['-on_date', 'currency'],
                'unique_together': {('currency', 'on_date')},
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Marked paid'), ('assigned', 'Assigned'), ('returned', 'Returned'), ('deleted', 'Deleted'), ('rate_override', 'Exchange rate overridden'), ('viewed', 'Viewed')], max_length=16)),
                ('object_type', models.CharField(choices=[('asset', 'Asset'), ('subscription', 'Subscription'), ('request', 'Request'), ('rate', 'Exchange rate'), ('report', 'Report')], max_length=14)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ Pound Sterling'), ('AUD', 'A$ Australian Dollar'), ('SGD', 'S$ Singapore Dollar'), ('AED', 'AED UAE Dirham'), ('CAD', 'C$ Canadian Dollar'), ('JPY', '¥ Japanese Yen')], default='INR', max_length=3)),
                ('amount_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fx_date', models.DateField(blank=True, null=True)),
                ('fx_missing', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('plan', models.CharField(blank=True, max_length=120)),
                ('cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-yearly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='monthly', max_length=12)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('renews_on', models.DateField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('seats', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_subscriptions', to='career_app.onboardingsubmission')),
            ],
            options={
                'db_table': 'finance_subscriptions',
                'ordering': ['renews_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('INR', '₹ Indian Rupee'), ('USD', '$ US Dollar'), ('EUR', '€ Euro'), ('GBP', '£ Pound Sterling'), ('AUD', 'A$ Australian Dollar'), ('SGD', 'S$ Singapore Dollar'), ('AED', 'AED UAE Dirham'), ('CAD', 'C$ Canadian Dollar'), ('JPY', '¥ Japanese Yen')], default='INR', max_length=3)),
                ('amount_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('fx_date', models.DateField(blank=True, null=True)),
                ('fx_missing', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('camera', 'Camera / Gear'), ('accessory', 'Accessory'), ('software', 'Software licence'), ('subscription', 'Subscription'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=20)),
                ('justification', models.TextField(blank=True)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('raised_on', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('purchased', 'Purchased'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('decided_by_name', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_on', models.DateField(blank=True, db_index=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('invoice_url', models.URLField(blank=True, max_length=1000)),
                ('invoice_no', models.CharField(blank=True, max_length=120)),
                ('paid_on', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_requests', to='finance_app.assetitem')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_requests', to='career_app.onboardingsubmission')),
                ('requested_by_admin', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_requests', to='finance_app.subscription')),
            ],
            options={
                'db_table': 'finance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['status', 'category'], name='finance_ass_status_ecac61_idx'),
        ),
        migrations.AddIndex(
            model_name='assetitem',
            index=models.Index(fields=['purchase_date'], name='finance_ass_purchas_00e488_idx'),
        ),
        migrations.AddIndex(
            model_name='financeauditlog',
            index=models.Index(fields=['object_type', 'object_id'], name='finance_aud_object__bcd351_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_active', 'renews_on'], name='finance_sub_is_acti_dcf101_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', '-created_at'], name='finance_req_status_959294_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['paid_on'], name='finance_req_paid_on_9b159e_idx'),
        ),
    ]
