# Generated by Django 6.0.6 on 2026-08-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitem',
            name='category_other',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='category_other',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
