# Generated by Django 6.0.6 on 2026-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0005_alter_teammember_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='certificate_template_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_template_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='certificate_template_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='certificate_template_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
