# Generated by Django 6.0.6 on 2026-07-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0007_alter_department_options_department_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_auto_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_duration_min',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_guests_see_each_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_hosts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_join_access',
            field=models.CharField(choices=[('open', 'Anyone with link'), ('org', 'Same org'), ('invited', 'Invited only')], default='invited', max_length=12),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_moderation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='meeting_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
