# Generated by Django 6.0.6 on 2026-07-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0008_eventregistration_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('cta_label', models.CharField(blank=True, default='Learn more', max_length=80)),
                ('cta_url', models.CharField(blank=True, default='/contact', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tech_products',
                'ordering': ['order', 'id'],
            },
        ),
    ]
