# Generated by Django 6.0.6 on 2026-08-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0012_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataapikey',
            name='scope',
            field=models.CharField(choices=[('submit', 'Write only (POST)'), ('read', 'Read only (GET)'), ('admin', 'Server-side: read + update records')], default='submit', max_length=10),
        ),
        migrations.CreateModel(
            name='DataSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='tiesverse_app.datastore')),
            ],
            options={
                'db_table': 'data_sequences',
                'constraints': [models.UniqueConstraint(fields=('store', 'name'), name='uniq_data_sequence_per_store')],
            },
        ),
    ]
