# Generated by Django 6.0.6 on 2026-08-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0013_alter_dataapikey_scope_datasequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('episode_label', models.CharField(blank=True, max_length=20)),
                ('tag', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('audio_url', models.CharField(blank=True, max_length=600)),
                ('cover_url', models.CharField(blank=True, max_length=600)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'podcasts',
                'ordering': ['position', '-published_at', '-created_at'],
            },
        ),
    ]
