# Generated by Django 6.0.6 on 2026-08-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0015_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('logo_url', models.CharField(blank=True, max_length=600)),
                ('has_transparency', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'talent_institutions',
                'ordering': ['position', 'id'],
            },
        ),
    ]
