# Generated by Django 6.0.6 on 2026-08-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0017_otpchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspeaker',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='tiesverse_app.eventregistration'),
        ),
        migrations.AddField(
            model_name='eventspeaker',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
