# Generated by Django 6.0.6 on 2026-08-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0020_mediapost_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'research_page',
            },
        ),
    ]
