# Generated by Django 6.0.6 on 2026-08-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0021_researchpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('eyebrow', models.CharField(blank=True, max_length=200)),
                ('dek', models.TextField(blank=True)),
                ('kind', models.CharField(default='Report', max_length=40)),
                ('date_label', models.CharField(blank=True, max_length=60)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'research_reports',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
