# Generated by Django 6.0.6 on 2026-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiesverse_app', '0022_researchreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='listen_url',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
