# Generated by Django 6.0.6 on 2026-07-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [ 
        ('webinar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=20)),
                ('event_title', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('email', 'Email'), ('phone', 'Phone'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkboxes')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('options', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_form_questions',
                'ordering': ['order', 'id'],
            },
        ),
    ]
