# Generated by Django 6.0.6 on 2026-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar_app', '0002_eventformquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventformquestion',
            name='maps_to',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='eventformquestion',
            name='section',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
