# Generated by Django 6.0.6 on 2026-08-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar_app', '0003_eventformquestion_maps_to_eventformquestion_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=20)),
                ('number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_form_sections',
                'ordering': ['order', 'number', 'id'],
                'unique_together': {('event_key', 'event_type', 'number')},
            },
        ),
    ]
